name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  EC618-SDK-Build:
    runs-on: ubuntu-latest
    strategy:    
      matrix:
        csdk_project: ["example", "luatos", "example_gpio", "example_adc", "example_socket", "libhttp_fota_iot", "example_psm", "example_record", "web_audio", "tracker", "example_ntp", "example_crypto", "example_audio_flash"]
    steps:
      - name: 克隆 LuatOS 代码库
        if: matrix.csdk_project == 'luatos'
        run:  git clone --depth=1 http://192.168.1.231:13000/openLuat/LuatOS.git
      - name: 克隆 ec618-csdk 代码库
        run:  git clone --depth=1 http://192.168.1.231:13000/openLuat/luatos-soc-2022.git
      - name: 安装 xmake
        run:  curl -fsSL https://xmake.io/shget.text | bash
      - name: 初始化工具链
        run: |
          mkdir tools
          cd tools
          wget -q http://192.168.1.231:18089/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
          tar xf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
          ls -l
          cd ..
          sed -i 's/security.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list
          sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list
          dpkg --add-architecture i386 && apt update
          apt-get install -y lib32z1 binutils:i386 libc6:i386 libgcc1:i386 libstdc++5:i386 libstdc++6:i386
      - name: 构建指定项目
        run: |
          export GCC_PATH=`pwd`/tools/gcc-arm-none-eabi-10.3-2021.10
          export XMAKE_MAIN_REPO=https://gitee.com/tboox/xmake-repo.git
          export LSPD_MODE=enable
          source ~/.xmake/profile
          cd luatos-soc-2022
          xmake -y --root
          rm -fr build
        env:
          PROJECT_NAME: ${{ matrix.csdk_project }}
